services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpassword
      POSTGRES_DB: springdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
